### ISSUE TITLE
Publish menu entry missing

### ISSUE THREAD

**Issue by georgeowell** [fraction/oasis#171]
**What's the problem you want solved?**
After latest commits, Publish is missing from the menu.

**Is there a solution you'd like to recommend?**
Add Publish to the sidebar menu.

**Comment by Powersource** [comment]
Yeah I was just gonna ask how to make a thread haha

**Comment by georgeowell** [comment]
> Yeah I was just gonna ask how to make a thread haha

We moved it to its own page in #160

In the meantime, you can find it at localhost:3000/publish

**Comment by georgeowell** [comment]
This is still not visible for me even with that latest commit! Did you test it?

**Comment by georgeowell** [comment]
hmm on @Powersource advice, I ran `npm start` directly in the repo instead. I must have messed some npm stuff up.

**Comment by christianbundy** [comment]
@georgeowell I'm curious if that changes #177 for you too, I think that should've been resolved in #162

**Comment by georgeowell** [comment]
@christianbundy I still can't see my own posts in latest :cry:
